### ISSUE TITLE
Default to infinite ` max_history_tokens`  to be backward compatible.

### ISSUE THREAD

**Issue by NirantK** [NirantK/agentai#11]
We should default to infinite ` max_history_tokens`  to be backward compatible.

_Originally posted by @NirantK in https://github.com/NirantK/agentai/pull/8#discussion_r1281711998_

**Comment by adivik2000** [comment]
Backward compatible as in have a list of all the messages in one list and that is trimmed based on the tokens given?

**Comment by NirantK** [comment]
Do not trim the Conversation by default at all. That is the existing behavior — we don't trim.
